### ISSUE TITLE
Average water level doesn’t correspond to the runtimes listed

### ISSUE THREAD

**Issue by FranzStein** [OpenSprinkler/OpenSprinkler-App#95] opened 2020-04-18 12:49 UTC
The average water level for a given day in the logs table doesn’t correspond to the runtimes listed for this given day. For example, a runtime of 21 min 36 sec with a basic runtime setting of 30 min should result in an average of 72%. This is not the case.  There is also a problem with the average water level listed next to the total runtime, which doesn’t seem to display a correct value. To avoid any misunderstandings a more detailed description of the logs view and especially the values listed might be helpful.

![LogsIssue](https://user-images.githubusercontent.com/48592222/79638034-bd02d600-8183-11ea-8982-42e6d887d6c8.JPG)

**Comment by salbahra** [comment] 2020-05-23 20:42
The watering percentage you are shown is the average watering level set on the controller over that period of time and not the percentage of scheduled watering. I hope this makes sense.

**Comment by FranzStein** [comment] 2020-05-24 09:19
Sorry, I still have some understanding problems.

I thought that the average water level listed next to the total runtime gives the average water level used by the controller over that period of time averaged over all watering events. In the above example this should result in: 1h 4 m 48 s = 60 x 60 x 1 + 60 x 4 + 48 s = 3888 s =64.8 m for 3 watering events or 21.6 m for 1 watering event -> As I have set my basic runtime to 30 m = 100 % -> 21.6 m / 30 m = 72%.

As already mentioned The average water level for a given day in the green logs table doesn’t correspond to the runtimes listed for this given day. Above runtime of 21 min 36 sec with a basic runtime setting of 30 min should result in an average of 72%. The 23% listed above seemed to be the calculated water level calculated at the end of this day?

Please have a look at the log given below. There shouldn't be a value of 25% listed, if there was no watering at all for that given day.

![LogView 2](https://user-images.githubusercontent.com/48592222/82750185-b2ed7c00-9dae-11ea-9695-5e62cb4968d5.JPG)

Maybe I have misunderstood something here and the whole issue isn't really important. Anyhow, I would be more than happy to get a clue on the calculations performed.

**Comment by rayshobby** [comment] 2020-05-24 14:39
Is it possible that some of your programs are not set to 'Use Weather'? As Samer described, the average watering level merely averages the water level numbers across the day, it is not based on the run time of the programs. If some of your programs are not set to 'Use Weather', then they are not affected by the watering level.

**Comment by FranzStein** [comment] 2020-05-24 16:34
There is only one program running.  This is set to 'Use Weather' and features three stations with a basic runtime of 30 minutes. The stations run consecutive once every 2nd day at 7 am in the morning with a delay of 30 seconds.

In the first example above, at April 13th, 2020 the program runs with a water level of 72% in the morning. The weather service updated the water level every two hours thereafter. The last update at about 11 pm this day ended with a water level of 23%. This 23% are shown as the average water level in the green logs table. I don't think that this is the correct average water level to be listed.

**Comment by rayshobby** [comment] 2020-05-24 17:15
There are several things that could be related so let me clarify:
1. Are you using the official opensprinkler weather server (at weather.opensprinkler.com) or are you using your own instance of the weather server code? The official opensprinkler weather server caches the weather data for 24 hours so the watering level across one day should be the same and does not vary. If you use your own instance of weather service, it can vary across a day and so the moment the program starts, the watering level may be different from the rest of the day when the watering level is sampled.

2. The way the app calculates the average watering level is as follows: it queries the firmware using command:
http://your_os_device_ip/jl?pw=xxx&start=yyy&end=zzz&type=wl
where xxx is the md5 checksum of the device password, yyy is the start time (in epoch time) and zzz is the end time. tyle=wl specifies that it wants the log to only contain water level values.
Then it looks at the water value numbers across one day and calculates its average. To reproduce the numbers, you can type in:
http://your_os_device_ip/jl?pw=xxx&hist=7&type=wl
where hist=7 asks the controller to return the past 7 days of water level data. The average of the returned list should match the 'Average Water Level' displayed at the top (above the per-day list). 

3. Regarding per-day average water level, it is possible that the app may be calculating the start and end times differently from using the local time (i.e. it might be using UTC+0 time instead of local time). But in any case, the per-day average number should match the average of a 24-hour window of a log window. If you have doubts, you can paste your result from running the above command (the hist=7) one, and we can take a look.

**Comment by FranzStein** [comment] 2020-05-25 08:04
1. I use my own instance of the weather server code: OpenSprinkler Weather Service v2.0.1 installed on a RaspberryPI getting its data via WeeWX from a Netatmo Weather Station. No changes are made to the software; the Zimmerman method is used.

2. I retrieved the water levels for April 13th, 2020 by using

http://your_os_device_ip/jl?pw=xxx&start=1586736000&end=1586736000&type=wl

Which results in:

[[0,"wl",64,1586736119],[0,"wl",67,1586743321],[0,"wl",70,1586750523],[0,"wl",72,1586757725],[0,"wl",74,1586765149],[0,"wl",75,1586772351],[0,"wl",76,1586779553],[0,"wl",72,1586786755],[0,"wl",64,1586793957],[0,"wl",44,1586801159],[0,"wl",32,1586808361],[0,"wl",23,1586815563]]

The water level (green) shown in the first log view above is taken from the sample [0,"wl",23,1586815563], which corresponds to April, 13th 2020, 22:06. Recalculating the average watering level results in (64+67+70+72+74+75+76+72+64+44+32+23)/12=733/12=61.08%, which is different from the average water level of 40.22% listed in the log view.

3. Water Levels for the last 7 days

[[0,"wl",45,1589679380],[0,"wl",47,1589686588],[0,"wl",49,1589693796],[0,"wl",51,1589701004],[0,"wl",52,1589708212],[0,"wl",54,1589715420],[0,"wl",55,1589722628],[0,"wl",56,1589729836],[0,"wl",56,1589737044],[0,"wl",57,1589744252],[0,"wl",57,1589751460],[0,"wl",57,1589758668],[0,"wl",56,1589765876],[0,"wl",55,1589773084],[0,"wl",55,1589780292],[0,"wl",55,1589788231],[0,"wl",55,1589795439],[0,"wl",56,1589802647],[0,"wl",58,1589809855],[0,"wl",61,1589817063],[0,"wl",62,1589824271],[0,"wl",64,1589831479],[0,"wl",66,1589838687],[0,"wl",68,1589845895],[0,"wl",70,1589853103],[0,"wl",73,1589860311],[0,"wl",75,1589867519],[0,"wl",77,1589874727],[0,"wl",79,1589881935],[0,"wl",79,1589889143],[0,"wl",80,1589896351],[0,"wl",81,1589903559],[0,"wl",84,1589915385],[0,"wl",85,1589922593],[0,"wl",88,1589929801],[0,"wl",90,1589937009],[0,"wl",91,1589944217],[0,"wl",93,1589951425],[0,"wl",97,1589963083],[0,"wl",97,1589970291],[0,"wl",96,1589977499],[0,"wl",91,1589984707],[0,"wl",87,1589991915],[0,"wl",82,1589999123],[0,"wl",79,1590006331],[0,"wl",76,1590013539],[0,"wl",75,1590020747],[0,"wl",74,1590027955],[0,"wl",74,1590035163],[0,"wl",73,1590042371],[0,"wl",71,1590049579],[0,"wl",70,1590056787],[0,"wl",71,1590063995],[0,"wl",74,1590071203],[0,"wl",77,1590078411],[0,"wl",80,1590085619],[0,"wl",83,1590092827],[0,"wl",84,1590100035],[0,"wl",84,1590107243],[0,"wl",84,1590114451],[0,"wl",83,1590121659],[0,"wl",82,1590128867],[0,"wl",83,1590136075],[0,"wl",84,1590143283],[0,"wl",85,1590150491],[0,"wl",86,1590157699],[0,"wl",87,1590164907],[0,"wl",87,1590172115],[0,"wl",87,1590179323],[0,"wl",89,1590186531],[0,"wl",89,1590186983],[0,"wl",93,1590194191],[0,"wl",93,1590201399],[0,"wl",96,1590208607],[0,"wl",100,1590215815],[0,"wl",102,1590223023],[0,"wl",100,1590230231],[0,"wl",99,1590231290],[0,"wl",90,1590238501],[0,"wl",77,1590245706],[0,"wl",58,1590252914],[0,"wl",46,1590260122],[0,"wl",35,1590267330],[0,"wl",25,1590274538],[0,"wl",16,1590281746],[0,"wl",11,1590288954],[0,"wl",5,1590296162],[0,"wl",0,1590303370],[0,"wl",0,1590310578],[0,"wl",0,1590317786],[0,"wl",0,1590324994],[0,"wl",7,1590332202],[0,"wl",19,1590339410],[0,"wl",26,1590346618]]

The water level (green) shown in the second log view above is taken from the sample [0,"wl",25,1590274538], which corresponds to May, 23th 2020, 22:55. Unfortunately, there was no watering at all on this specific day.

Maybe you can have a closer look on the calculations performed?

**Comment by salbahra** [comment] 2023-07-23 18:51
A lot has changed over the last three years and since no recent comments are here I'm going to close this issue. If you are still having this issue against the latest software please let us know.

**Closed by salbahra** 2023-07-23 18:52 UTC
