### ISSUE TITLE
Bottom bar 'last ran station' does not display date/time properly

### ISSUE THREAD

**Issue by kpfleming** [OpenSprinkler/OpenSprinkler-App#132] opened 2022-05-04 10:40 UTC
App Version: 2.2.5
Firmware: 2.1.9 (3)
Hardware Version: OSPi

I've tested this with both Chromium and Firefox, and also using my local UI server and the public one. In all cases, the bottom bar doesn't display the date/time of the last program run correctly:

![image](https://user-images.githubusercontent.com/305938/166666544-8555ee81-13ed-437f-8a3b-96e09f54111c.png)

When I open the app the date/time displayed are very strange (a 5-digit year), but then a few seconds later the display changes to what is shown above.

**Comment by salbahra** [comment] 2023-07-23 18:54
Is this still occurring against the latest firmware and app?

If so, please share the /ja reply from the device please.

Thank you!

**Comment by kpfleming** [comment] 2023-07-24 14:05
Sorry, I can no longer provide assistance on this issue as I stopped using OpenSprinkler some time ago.

**Comment by salbahra** [comment] 2023-07-24 14:07
Thank you for your update! I can't reproduce this issue and am going to close this then.

**Closed by salbahra** 2023-07-24 14:07 UTC
